### ISSUE TITLE
Should not return HTML in scramblers.

### ISSUE THREAD

**Issue by jgouly** [cubing/mark2#105]
The Clock scrambler currently returns HTML as part of the scramble.

Should this be a default? Should there be a .scramble and a formattedScramble?

**Comment by lgarron** [comment]
Oh, _this_ is what the others meant on IRC.

Yes, I've been meaning to change everything to plain-text scrambles because it's more consistent. Eventually I want a consistent way to handle algorithms and scramble formatting (e.g. to interact with twisty.js).

I've been hoping [this thread](http://www.speedsolving.com/forum/showthread.php?34120-WCA-Regulations-2012-Clock-Notation) converges on a good notation to switch to.
